### ISSUE TITLE
Parse commandline arguments of engines

### ISSUE THREAD

**Issue by Entze** [rpdelaney/python-chess-annotator#12]
When taking an engine as argument the program should be able to parse the options given by the user. This is required by some engines. Gnuchess only starts in UCI mode with the `-u` (`--uci`) argument.

**Comment by rpdelaney** [comment]
I'm having trouble getting gnuchess to compile on OSX for testing. I may be able to try it on my linux machine when I get home. In the mean time, do you know of any other engines that accept or require runtime parameters?

**Comment by Entze** [comment]
@rpdelaney I figure you could use an optional argument of stockfish for debugging. Why do you need to compile gnuchess? Aren't there binaries for MacOs?

For now there is a temporary solution: `gnuchess` usually comes with the `gnuchessu` variant which is equivalent to `gnuchess -u`. I was able to verify that this works.

**Comment by rpdelaney** [comment]
I might be missing something but it looks like this isn't possible with python-chess. Could a wrapper script work? I tried testing it, but `gnuchess -u` still doesn't give me a uci interface after I tried installing it in archlinux.

**Comment by niklasf** [comment]
python-chess would accept `["gnuchess", "-u"]` in all places that accept `"stockfish"`.

**Comment by rpdelaney** [comment]
If it also accepts `["stockfish"]` then this is a trivial fix

**Comment by niklasf** [comment]
Cool. It does/should.

**Comment by rpdelaney** [comment]
Hm. seems gnuchess has a poor implementation of the UCI spec. After 9b6ff9a :

```
$ python3 annotator/__main__.py -e "gnuchess -u" -f data/caruana-kasparov.pgn

An unhandled exception occurred: <class 'TypeError'>
Traceback (most recent call last):
  File "annotator/__main__.py", line 807, in <module>
    main()
  File "annotator/__main__.py", line 797, in main
    raise e
  File "annotator/__main__.py", line 790, in main
    engine, args.threads)
  File "annotator/__main__.py", line 747, in analyze_game
    node.root().headers["Annotator"] = annotator
  File "/usr/local/lib/python3.7/site-packages/chess/pgn.py", line 549, in __setitem__
    elif "\n" in value or "\r" in value:
TypeError: argument of type 'NoneType' is not iterable
```
Stand by......
