### ISSUE TITLE
add ?!, ? and ??

### ISSUE THREAD

**Issue by Entze** [rpdelaney/python-chess-annotator#15]
Now the annotator only inserts the numeric codes. In addition it could annotate the widely used `?!` (Inaccuracy), `?` (Mistake) and `??` (Blunder)

#14 has an example of an annotated game that uses those symbols.

**Comment by rpdelaney** [comment]
I'll double check later but I don't think python-chess supports this.

**Comment by rpdelaney** [comment]
Per python-chess [docs](http://python-chess.readthedocs.io/en/latest/pgn.html#nags):

```
During PGN parsing, annotations like !, ?, !!, etc., are also converted to NAGs.
```

So unless there are changes to python-chess, we can't do this. I suggest you raise a feature request with Niklas to support adding the 'plaintext' annotations to a GameNode. If that is implemented in python-chess, we can revisit this.
